const Actions = {
  FETCH_CURRENCIES: 'FETCH_CURRENCIES',
  FETCH_PORTFOLIO: 'FETCH_PORTFOLIO',
  SIGNUP: 'SIGNUP',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SET_USER: 'SET_USER',
};

export default Actions;
