const Actions = {
  DISMISS_ERROR: 'DISMISS_ERROR',
  FETCH_CURRENCIES: 'FETCH_CURRENCIES',
  FETCH_PORTFOLIO: 'FETCH_PORTFOLIO',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SAVE_PORTFOLIO: 'SAVE_PORTFOLIO',
  SET_USER: 'SET_USER',
  SIGNUP: 'SIGNUP',
};

export default Actions;
